# Generated by Django 4.2.8 on 2023-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('is_despo', models.CharField(max_length=254)),
                ('nbr_place', models.CharField(max_length=20)),
            ],
        ),
    ]
